/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/player.glb --output player-info.jsx 
Author: Lean_Lo1786 (https://sketchfab.com/pepito37383)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-rigged-cristiano-ronaldo-al-nassr-1424fba6eedb4d54a2621284f149a96c
Title: 3D Rigged Cristiano Ronaldo Al Nassr
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/player.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.texture_2} skeleton={nodes.Object_9.skeleton} />
        <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.texture_8} skeleton={nodes.Object_10.skeleton} />
        <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.texture_5} skeleton={nodes.Object_11.skeleton} />
        <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.texture_3} skeleton={nodes.Object_12.skeleton} />
        <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.texture_4} skeleton={nodes.Object_13.skeleton} />
        <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.texture_6} skeleton={nodes.Object_14.skeleton} />
        <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.texture_1} skeleton={nodes.Object_15.skeleton} />
        <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.texture_7} skeleton={nodes.Object_16.skeleton} />
        <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.texture_9} skeleton={nodes.Object_17.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/player.glb')
